name: CI to Docker Hub
on:
  push:
    branches: [ example_homework ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        docker_context: [./app, ./database, ./reverse_proxy, ./payment_gateway]

    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push 
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.docker_context }}
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/atsea-sample-shop-app:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
